# Default values for kubernetes-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: boostport/kubernetes-vault
service:
  dummyPort: 80
vault:
  address: http://vault:8200
  token: your-vault-token
  vaultCertBackend: intermediate-ca
  vaultCertRole: kubernetes-vault
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

