apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  clusterIP: None
  ports:
    - name: port
      port: {{ .Values.service.dummyPort }}
  selector:
    run: {{ template "fullname" . }}
